#!/bin/bash

# First argument: Client identifier
cat /root/clients/client.ovpn.template \
    <(echo -e '<ca>') \
    /root/easy-rsa/pki/ca.crt \
    <(echo -e '</ca>\n<cert>') \
    /root/easy-rsa/pki/issued/${1}.crt \
    <(echo -e '</cert>\n<key>') \
    /root/easy-rsa/pki/private/${1}.key \
    <(echo -e '</key>\n<tls-crypt>') \
    /etc/openvpn/server/ta.key \
    <(echo -e '</tls-crypt>') \
    > /tmp/${1}.ovpn.template

envsubst < /tmp/${1}.ovpn.template > /root/clients/${1}.ovpn
chown $DEV_UID:$DEV_GID /root/clients/${1}.ovpn
